/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AllFrames;

import javax.swing.JOptionPane;

/**
 *
 * @author Sobhani Family
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form Frame01
     */
    public WelcomeFrame() {
       initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CLogo = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(107, 196, 249));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 76, 130));
        jLabel1.setText("AVICENNA PHARMACY MANAGMENT SYSTEM ");
        BackGroundPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 224, -1, 40));

        CLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sobhani Family\\Downloads\\vbb-removebg-preview.png")); // NOI18N
        CLogo.setText("hh");
        BackGroundPanel.add(CLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 417, 300));
        BackGroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 519, 1010, -1));

        LoadingLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LoadingLabel.setText("Loading.....");
        BackGroundPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 495, -1, -1));

        LoadingValue.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LoadingValue.setText("0 %");
        BackGroundPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WelcomeFrame().setVisible(true);
//            }
//        });
      WelcomeFrame sp = new WelcomeFrame();
      sp.setVisible(true);
      Login login = new Login();
      try{
          for(int i=0; i<=100;i++){
          Thread.sleep(60);
          sp.LoadingValue.setText(i + "%");
          if(i==10){
             sp.LoadingLabel.setText("Turning on Modules....");
          }
          if(i==20){
             sp.LoadingLabel.setText("Loading Modules....");
          }
          if(i==30){
             sp.LoadingLabel.setText("Connecting to Database....");
          }
          if(i==40){
             sp.LoadingLabel.setText("Checking Server....");
          }
          if(i==50){
             sp.LoadingLabel.setText("Connecting to Database....");
          }
          if(i==60){
             sp.LoadingLabel.setText("Connection Successful");
          }
          if(i==70){
             sp.LoadingLabel.setText("Launching Application....");
          }
          if(i==80){
             sp.LoadingLabel.setText("Finishing Soon....");
          }
          sp.LoadingBar.setValue(i);
        }     
}catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}
      sp.setVisible(false);
      login.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel CLogo;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
